# Generated by Django 3.2.6 on 2024-04-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorOfertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='correo',
            field=models.EmailField(default='correo@default.com', max_length=254),
        ),
    ]
