# Generated by Django 3.2.6 on 2024-04-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorOfertas', '0002_oferta_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='correo',
        ),
    ]
