# Generated by Django 3.2.6 on 2024-04-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorOfertas', '0004_oferta_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='correo',
            field=models.EmailField(default='correo@default.com', max_length=254),
        ),
    ]
