# Generated by Django 3.2.6 on 2024-05-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorSolicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manejadorsolicitudes',
            name='correo',
            field=models.EmailField(default='prueba@gmail.com', max_length=254),
        ),
    ]
